### PR TITLE
#177 Drop git, in-memory, postgres storage support, clean unused code

### PR DESCRIPTION
**Pull request by hzenginx**
Work on #177 
I just kept codes required for registry support.
Altered some tests.

### CODE REVIEW

**Comment by netme** [comment]
@hzenginx just for my understanding: once we will remove this code, pazuzu will still work with the current version of registry, right?

**Comment by netme** [comment]
And please create an GH issue to keep track on why this change was made :-)

**Comment by hzenginx** [comment]
@netme yeap it will work, there is no api changes in this pr. I only removed some unused code and other features we planned to drop.
Opening a issue now, after we finalised cleanup we also need to do some updates in readme too.

**Comment by hzenginx** [comment]
@netme I want to merge this today, there is more work to do in CLI and this is blocking

**Comment by netme** [comment]
@hzenginx , sorry, completely forgot about it. Go for it

**Comment by netme** [comment]
👍

**Comment by hzenginx** [comment]
🍺

**Pull request merged**
