### PR TITLE
Move out few hardcoded constants.

### PR DESCRIPTION
**Pull request by erthalion**
Few of them was used only for the testing purposes (like `DefaultShell`
in `pazuzu.go`), but I believe that it's not an excuse, since tests also
should be clean. The same for `MakeShellCommand` function.

### CODE REVIEW

**Comment by slothspot** [comment]
I propose to move test spec file name to pazuzu as well, but it may be done in separate commit

**Comment by erthalion** [comment]
> I propose to move test spec file name to pazuzu as well, but it may be done in separate commit

And, basically, you already did this in #227, am I right?

**Comment by slothspot** [comment]
Yes :)

**Comment by slothspot** [comment]
👍

**Pull request merged**
