### PR TITLE
Refactor errors

### PR DESCRIPTION
**Pull request by jyun-zalando**
Issue #105

### CODE REVIEW

**Comment by netme** [comment]
I have quite a bit different opinion on this approach. It would be great if we'll have 2 `error` modules: on `pazuzu` and `cli/pazuzu` levels. The ones on `cli/pazuzu` should serve only CLI needs and error messages might be oriented to the end-user. 

Let's also ask @rdllopes and @olafmaurer

**Comment by jyun-zalando** [comment]
@netme Yes, I agree with you. And ...

* How about to just specialize only some kind of errors for CLI-app?
  * ..Then we get separated `/error.go` and `/cli/pazuzu/error.go`.

Thanks.

**Comment by netme** [comment]
@jyun-zalando makes complete sense

**Comment by jyun-zalando** [comment]
There were conflicts. (Because some changes are already merged before.)

**Comment by jyun-zalando** [comment]
👍

**Comment by jyun-zalando** [comment]
👍

**Comment by netme** [comment]
Makes sense, thanks for taking care of it

**Pull request merged**
